spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ProjectX
    username: root
    password: Pavan@2010
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect



